FACEBOOK_APP_ID: "1159750564103622"
FACEBOOK_APP_SECRET: "ab5d6e55f9b5601c6a8bb85f79e6f282"

GOOGLE_OAUTH2_APP_ID: "359121309262-mtbggh6tmegl36rdc86h1h44p8tq7lqk.apps.googleusercontent.com"
GOOGLE_OAUTH2_APP_SECRET: "yTtAMyin6W_bM-ODGzWBv6DN"

TWITTER_APP_ID: "628Gol2tJrgr4jtsiHWBpdb3t"
TWITTER_APP_SECRET: "f26pyQ2FYveA33ECkAtnnweMQWzMVqMOvYKDHaMheQ8VIzlGrS"

MAILGUN_DOMAIN: "sandboxcabac8c05d9b4598b388e59b44ae042b.mailgun.org"
MAILGUN_USERNAME: "postmaster@sandboxcabac8c05d9b4598b388e59b44ae042b.mailgun.org"
MAILGUN_PASSWORD: "d242003133b0ee3109a448343bedced0"

SENDGRID_USERNAME: "tuananhht94"
SENDGRID_PASSWORD: "tuananha1"

CHATWORK_API_KEY: "4b8cb6983ee76a42c36926f6ff76315c"
