male_gender: true
female_gender: false
products_per_page: 9
avatar_default: "default_avatar.png"
avatar_medium: 160
resize_avatar: 500
product_default: "default_production.png"
fb_sharer: "https://www.facebook.com/sharer/sharer.php?u="
class_default: "default"
class_danger: "danger"
sold_out: 0
file_path_404: "/public/404.html"
http_status: {not_found: 404}
round_to_hundredth: 2
empty_cart: 0
minimum_quantity: 1
init_quantity: 1
