male_gender: true
female_gender: false
products_per_page: 9
avatar_default: "default_avatar.png"
avatar_medium: 160
resize_avatar: 500
product_default: "default_production.png"
fb_sharer: "https://www.facebook.com/sharer/sharer.php?u="
class_default: "default"
class_danger: "danger"
file_path_404: "/public/404.html"
http_status: {success: 200, bad_request: 400, not_found: 404}
round_to_hundredth: 2
empty_cart: 0
minimum_quantity: 1
init_quantity: 1
no_rating: {value_rating: 0, count_rating: 0}
zero: 0
cookie_live: 1
recent_products_size: 10
class_active: "active"
gender_val: {"Male": true, "Female": false}
order_status_classes: {pending: "danger", done: "primary", canceled: "default"}
order_status: {pending: 0, done: 1, canceled: 2}
order_status_in_word: {pending: "pending", done: "done", canceled: "canceled"}
id_chatwork_group: 61067695
date_range: {one_week: 7, one_month: 30}
top_product: 10
order_per_page: 20
line_break: "<br/>"
js_line_break: "/n"
sold_out: 0
suggestion_per_page: 20
user_per_page: 20
roles: {admin: "admin", mod: "mod", member: "member"}
top_new_limit: 6
hot_trend_limit: 6
time_format: "%d%m%Y"
type_xls: "text/xls; charset=utf-8; header=present"
product_filters_rating: {highest_rate: "Highest"}
product_filters: {price_decrease: "Decrease", price_increase: "Increase" , get_all: "All"}
